In [1]:
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
from scipy import stats

In [2]:
tickets = pd.read_csv('parking_citations.corrupted.csv')

C:\Users\rtorp\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

# Exploratory Data Analysis

In [3]:
print(len(tickets))

8726014

In [4]:
tickets.head(25)

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
0,1103341116,2015-12-21T00:00:00,1251.0,NaN,NaN,CA,200304.0,NaN,NaN,PA,GY,13147 WELBY WAY,01521,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
1,1103700150,2015-12-21T00:00:00,1435.0,NaN,NaN,CA,201512.0,NaN,NaN,VN,WH,525 S MAIN ST,1C51,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
2,1104803000,2015-12-21T00:00:00,2055.0,NaN,NaN,CA,201503.0,NaN,NaN,PA,BK,200 WORLD WAY,2R2,2.0,8939,WHITE CURB,58.0,6439997.9,1802686.4
3,1104820732,2015-12-26T00:00:00,1515.0,NaN,NaN,CA,NaN,NaN,NaN,PA,WH,100 WORLD WAY,2F11,2.0,000,17104h,NaN,6440041.1,1802686.2
4,1105461453,2015-09-15T00:00:00,115.0,NaN,NaN,CA,200316.0,NaN,CHEV,PA,BK,GEORGIA ST/OLYMPIC,1FB70,1.0,8069A,NO STOPPING/STANDING,93.0,99999.0,99999.0
5,1106226590,2015-09-15T00:00:00,19.0,NaN,NaN,CA,201507.0,NaN,NaN,VN,GY,SAN PEDRO S/O BOYD,1A35W,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
6,1106500452,2015-12-17T00:00:00,1710.0,NaN,NaN,CA,201605.0,NaN,MAZD,PA,BL,SUNSET/ALVARADO,00217,1.0,8070,PARK IN GRID LOCK ZN,163.0,99999.0,99999.0
7,1106500463,2015-12-17T00:00:00,1710.0,NaN,NaN,CA,201602.0,NaN,NaN,PA,BK,SUNSET/ALVARADO,00217,1.0,8070,PARK IN GRID LOCK ZN,163.0,99999.0,99999.0
8,1106506402,2015-12-22T00:00:00,945.0,NaN,NaN,CA,201605.0,NaN,NaN,PA,BR,721 S WESTLAKE,2A75,1.0,8069AA,NO STOP/STAND AM,93.0,99999.0,99999.0
9,1106506413,2015-12-22T00:00:00,1100.0,NaN,NaN,CA,201701.0,NaN,NaN,PA,SI,1159 HUNTLEY DR,2A75,1.0,8069AA,NO STOP/STAND AM,93.0,99999.0,99999.0
10,1106506424,2015-12-22T00:00:00,1100.0,NaN,NaN,CA,201511.0,NaN,FORD,TR,WH,1159 HUNTLEY DR,2A75,1.0,8069AA,NO STOP/STAND AM,93.0,99999.0,99999.0
11,1106506435,2015-12-22T00:00:00,1105.0,NaN,NaN,CA,201701.0,NaN,CHRY,PA,GO,1159 HUNTLEY DR,2A75,1.0,8069AA,NO STOP/STAND AM,93.0,99999.0,99999.0
12,1106506446,2015-12-22T00:00:00,1110.0,NaN,NaN,CA,201511.0,NaN,NaN,PA,BK,1200 W MIRAMAR,2A75,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
13,1106549754,2015-12-15T00:00:00,825.0,NaN,NaN,CA,201607.0,NaN,NaN,TR,BK,4TH/STATE,CM96,1.0,8069A,NO STOPPING/STANDING,93.0,99999.0,99999.0
14,1107179581,2015-12-27T00:00:00,1055.0,NaN,NaN,CA,201605.0,NaN,TOYO,PA,BK,3100 N HOLLYRIDGE DR,NaN,54.0,8058L,PREF PARKING,68.0,99999.0,99999.0
15,1107179592,2015-12-27T00:00:00,1200.0,NaN,NaN,CA,201602.0,NaN,NaN,PA,BK,3115 N BERENDO DR,NaN,54.0,8058L,PREF PARKING,68.0,99999.0,99999.0
16,1107179603,2015-12-27T00:00:00,1400.0,NaN,NaN,CA,201611.0,NaN,NaN,PA,WH,3100 N BEACHWOOD DR,NaN,54.0,8058L,PREF PARKING,68.0,99999.0,99999.0
17,1107539823,2015-09-16T00:00:00,2120.0,NaN,NaN,CA,201502.0,NaN,NaN,PA,NaN,BLAINE/11TH PL,1FB95,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
18,1107539834,2015-09-16T00:00:00,1045.0,NaN,NaN,CA,NaN,NaN,CHEV,PA,BK,1246 S FIGUEROA ST,1L20,1.0,8069AP,NO STOP/STAND PM,93.0,99999.0,99999.0
19,1107780811,2015-12-22T00:00:00,1102.0,NaN,NaN,CA,201606.0,NaN,HOND,PA,BK,PLATA/RAMPART,2A1,1.0,8069B,NO PARKING,73.0,99999.0,99999.0
20,1107780822,2015-12-22T00:00:00,1105.0,NaN,NaN,FL,201611.0,NaN,NaN,PA,WH,NaN,2A1,1.0,8069B,NO PARKING,73.0,99999.0,99999.0
21,1107973985,2015-12-18T00:00:00,1920.0,NaN,NaN,CA,201509.0,NaN,NISS,PA,BK,VICAR/CASTLE HEIGHTS,8A95,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
22,1107973996,2015-12-18T00:00:00,1930.0,NaN,NaN,CA,201511.0,NaN,HOND,PA,BK,REGENT ST/IVY ST,8A95,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
23,1107978852,2015-12-18T00:00:00,1900.0,NaN,NaN,CA,201511.0,NaN,NaN,PA,SI,1707 GLENDON AV,8A29,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
24,1108311002,2015-12-22T00:00:00,140.0,NaN,NaN,CA,201603.0,NaN,NaN,PA,RE,12113 BURBANK BL,01532,1.0,5200A,DSPLYPLATE A,25.0,99999.0,99999.0

In [5]:
tickets.describe()

,Issue time,Marked Time,Plate Expiry Date,Agency,Fine amount,Latitude,Longitude
count,8.723431e+06,290599.000000,7.931187e+06,8.725469e+06,8.719507e+06,8.726011e+06,8.726011e+06
mean,1.203930e+03,1055.399286,1.867823e+05,5.200932e+01,7.011293e+01,5.501648e+06,1.586792e+06
std,4.722413e+02,227.596205,5.276278e+04,9.301675e+00,3.211512e+01,3.004177e+06,2.065458e+06
min,0.000000e+00,1.000000,1.000000e+00,1.000000e+00,1.000000e+01,9.999900e+04,9.999900e+04
25%,9.120000e+02,910.000000,2.016010e+05,5.100000e+01,6.300000e+01,6.421512e+06,1.821558e+06
50%,1.156000e+03,1035.000000,2.017020e+05,5.400000e+01,6.800000e+01,6.451540e+06,1.841987e+06
75%,1.511000e+03,1200.000000,2.018030e+05,5.500000e+01,7.300000e+01,6.475013e+06,1.858207e+06
max,2.359000e+03,2400.000000,8.201080e+05,9.700000e+01,5.050000e+02,4.042322e+09,4.042322e+09

In [6]:
tickets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8726014 entries, 0 to 8726013
Data columns (total 19 columns):
Ticket number            object
Issue Date               object
Issue time               float64
Meter Id                 object
Marked Time              float64
RP State Plate           object
Plate Expiry Date        float64
VIN                      object
Make                     object
Body Style               object
Color                    object
Location                 object
Route                    object
Agency                   float64
Violation code           object
Violation Description    object
Fine amount              float64
Latitude                 float64
Longitude                float64
dtypes: float64(7), object(12)
memory usage: 1.2+ GB

In [7]:
len(tickets[tickets.Make.notnull()])

4357544

In [60]:
len(tickets[tickets['Plate Expiry Date'] < 200001])

586142

#  Create Modeling Dataset

In [19]:
tic_mod = tickets[tickets.Make.notnull()]

In [20]:
tic_mod.reset_index(drop=True, inplace=True)

In [26]:
tic_mod['Plate Expiry Date'].tail(100)

4357444    201912.0
4357445    201907.0
4357446    201912.0
4357447    201903.0
4357448    201907.0
4357449    201911.0
4357450    201908.0
4357451    201902.0
4357452    201902.0
4357453    201910.0
4357454    201807.0
4357455    201905.0
4357456         NaN
4357457    201910.0
4357458    201912.0
4357459    201903.0
4357460    202001.0
4357461    201910.0
4357462    202001.0
4357463    201903.0
4357464         NaN
4357465    202002.0
4357466    201905.0
4357467    201902.0
4357468    201906.0
4357469    201809.0
4357470         NaN
4357471    201810.0
4357472    201810.0
4357473    201910.0
             ...
4357514    201905.0
4357515    201904.0
4357516    201909.0
4357517    201904.0
4357518    201905.0
4357519         NaN
4357520    201907.0
4357521    201910.0
4357522         NaN
4357523    201906.0
4357524    201904.0
4357525    201812.0
4357526    201909.0
4357527    201905.0
4357528    201808.0
4357529    201812.0
4357530    201908.0
4357531    201906.0
4357532         NaN
4357533    201910.0
4357534    201805.0
4357535    201903.0
4357536    201811.0
4357537    201808.0
4357538         NaN
4357539         NaN
4357540    201909.0
4357541    201905.0
4357542    201912.0
4357543    201905.0
Name: Plate Expiry Date, Length: 100, dtype: float64

In [29]:
tic_mod.head()

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
0,1105461453,2015-09-15T00:00:00,115.0,NaN,NaN,CA,200316.0,NaN,CHEV,PA,BK,GEORGIA ST/OLYMPIC,1FB70,1.0,8069A,NO STOPPING/STANDING,93.0,99999.0,99999.0
1,1106500452,2015-12-17T00:00:00,1710.0,NaN,NaN,CA,201605.0,NaN,MAZD,PA,BL,SUNSET/ALVARADO,00217,1.0,8070,PARK IN GRID LOCK ZN,163.0,99999.0,99999.0
2,1106506424,2015-12-22T00:00:00,1100.0,NaN,NaN,CA,201511.0,NaN,FORD,TR,WH,1159 HUNTLEY DR,2A75,1.0,8069AA,NO STOP/STAND AM,93.0,99999.0,99999.0
3,1106506435,2015-12-22T00:00:00,1105.0,NaN,NaN,CA,201701.0,NaN,CHRY,PA,GO,1159 HUNTLEY DR,2A75,1.0,8069AA,NO STOP/STAND AM,93.0,99999.0,99999.0
4,1107179581,2015-12-27T00:00:00,1055.0,NaN,NaN,CA,201605.0,NaN,TOYO,PA,BK,3100 N HOLLYRIDGE DR,NaN,54.0,8058L,PREF PARKING,68.0,99999.0,99999.0

In [27]:
stats.mode(pd.to_numeric(tic_mod['Plate Expiry Date']).fillna(0).astype(np.int))

ModeResult(mode=array([0]), count=array([396547]))

In [30]:
tic_mod['Issue Date Fixed'] = pd.to_datetime(tic_mod['Issue Date'], infer_datetime_format = True)
tic_mod['Plate Expiry Date Num'] = pd.to_numeric(tic_mod['Plate Expiry Date']).fillna(0).astype(np.int)

C:\Users\rtorp\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\rtorp\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [108]:
### Drop Plate Expiry Dates before 1990 and after 2019 and records with month > 12 or =0

tic_mod = tic_mod[(tic_mod['Plate Expiry Date Num'] < 202001) & (tic_mod['Plate Expiry Date Num'] > 198912) & (tic_mod['Plate Expiry Date Num'] % 100 < 13) & (tic_mod['Plate Expiry Date Num'] % 100 > 0)]

In [109]:
print(tic_mod[tic_mod['Plate Expiry Date Num'] > 0].groupby('Plate Expiry Date Num')['Plate Expiry Date Num'].size().sort_values(ascending=False).head())

Plate Expiry Date Num
201606    83989
201706    83725
201708    82718
201608    82383
201703    81494
Name: Plate Expiry Date Num, dtype: int64

In [110]:
tic_mod['Plate Expiry Date Num'].max()

201912

In [111]:
tic_mod[tic_mod['Plate Expiry Date Num'] % 100 >12]

Empty DataFrame
Columns: [Ticket number, Issue Date, Issue time, Meter Id, Marked Time, RP State Plate, Plate Expiry Date, VIN, Make, Body Style, Color, Location, Route, Agency, Violation code, Violation Description, Fine amount, Latitude, Longitude, Issue Date Fixed, Plate Expiry Date Num, Plate String, Plate Expiry Date Fixed]
Index: []

[0 rows x 23 columns]

In [112]:
tic_mod.head()

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,...,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude,Issue Date Fixed,Plate Expiry Date Num,Plate String,Plate Expiry Date Fixed
1,1106500452,2015-12-17T00:00:00,1710.0,NaN,NaN,CA,201605.0,NaN,MAZD,PA,...,1.0,8070,PARK IN GRID LOCK ZN,163.0,99999.0,99999.0,2015-12-17,201605,201605,1970-01-01 00:00:00.000201605
2,1106506424,2015-12-22T00:00:00,1100.0,NaN,NaN,CA,201511.0,NaN,FORD,TR,...,1.0,8069AA,NO STOP/STAND AM,93.0,99999.0,99999.0,2015-12-22,201511,201511,1970-01-01 00:00:00.000201511
3,1106506435,2015-12-22T00:00:00,1105.0,NaN,NaN,CA,201701.0,NaN,CHRY,PA,...,1.0,8069AA,NO STOP/STAND AM,93.0,99999.0,99999.0,2015-12-22,201701,201701,1970-01-01 00:00:00.000201701
4,1107179581,2015-12-27T00:00:00,1055.0,NaN,NaN,CA,201605.0,NaN,TOYO,PA,...,54.0,8058L,PREF PARKING,68.0,99999.0,99999.0,2015-12-27,201605,201605,1970-01-01 00:00:00.000201605
6,1107780811,2015-12-22T00:00:00,1102.0,NaN,NaN,CA,201606.0,NaN,HOND,PA,...,1.0,8069B,NO PARKING,73.0,99999.0,99999.0,2015-12-22,201606,201606,1970-01-01 00:00:00.000201606

In [114]:
tic_mod['Plate Expiry Date Fixed'] = pd.to_datetime(tic_mod['Plate Expiry Date Num'], format='%Y%m')

In [115]:
tic_mod.head()

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,...,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude,Issue Date Fixed,Plate Expiry Date Num,Plate String,Plate Expiry Date Fixed
1,1106500452,2015-12-17T00:00:00,1710.0,NaN,NaN,CA,201605.0,NaN,MAZD,PA,...,1.0,8070,PARK IN GRID LOCK ZN,163.0,99999.0,99999.0,2015-12-17,201605,201605,2016-05-01
2,1106506424,2015-12-22T00:00:00,1100.0,NaN,NaN,CA,201511.0,NaN,FORD,TR,...,1.0,8069AA,NO STOP/STAND AM,93.0,99999.0,99999.0,2015-12-22,201511,201511,2015-11-01
3,1106506435,2015-12-22T00:00:00,1105.0,NaN,NaN,CA,201701.0,NaN,CHRY,PA,...,1.0,8069AA,NO STOP/STAND AM,93.0,99999.0,99999.0,2015-12-22,201701,201701,2017-01-01
4,1107179581,2015-12-27T00:00:00,1055.0,NaN,NaN,CA,201605.0,NaN,TOYO,PA,...,54.0,8058L,PREF PARKING,68.0,99999.0,99999.0,2015-12-27,201605,201605,2016-05-01
6,1107780811,2015-12-22T00:00:00,1102.0,NaN,NaN,CA,201606.0,NaN,HOND,PA,...,1.0,8069B,NO PARKING,73.0,99999.0,99999.0,2015-12-22,201606,201606,2016-06-01

In [10]:
top25 = list(tic_mod.groupby('Make')['Make'].size().sort_values(ascending=False).head(25).index)
top25

['TOYT',
 'HOND',
 'FORD',
 'NISS',
 'CHEV',
 'BMW',
 'MERZ',
 'VOLK',
 'HYUN',
 'DODG',
 'LEXS',
 'KIA',
 'JEEP',
 'AUDI',
 'MAZD',
 'OTHR',
 'GMC',
 'CHRY',
 'INFI',
 'ACUR',
 'SUBA',
 'VOLV',
 'TOYO',
 'MITS',
 'CADI']

In [11]:
tic_mod.Top25 = np.where(tic_mod.Make.isin(top25), 1,0)
tic_mod.head(25)

C:\Users\robto\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  if __name__ == '__main__':

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
4,1105461453,2015-09-15T00:00:00,115.0,NaN,NaN,CA,200316.0,NaN,CHEV,PA,BK,GEORGIA ST/OLYMPIC,1FB70,1.0,8069A,NO STOPPING/STANDING,93.0,99999.0,99999.0
6,1106500452,2015-12-17T00:00:00,1710.0,NaN,NaN,CA,201605.0,NaN,MAZD,PA,BL,SUNSET/ALVARADO,00217,1.0,8070,PARK IN GRID LOCK ZN,163.0,99999.0,99999.0
10,1106506424,2015-12-22T00:00:00,1100.0,NaN,NaN,CA,201511.0,NaN,FORD,TR,WH,1159 HUNTLEY DR,2A75,1.0,8069AA,NO STOP/STAND AM,93.0,99999.0,99999.0
11,1106506435,2015-12-22T00:00:00,1105.0,NaN,NaN,CA,201701.0,NaN,CHRY,PA,GO,1159 HUNTLEY DR,2A75,1.0,8069AA,NO STOP/STAND AM,93.0,99999.0,99999.0
14,1107179581,2015-12-27T00:00:00,1055.0,NaN,NaN,CA,201605.0,NaN,TOYO,PA,BK,3100 N HOLLYRIDGE DR,NaN,54.0,8058L,PREF PARKING,68.0,99999.0,99999.0
18,1107539834,2015-09-16T00:00:00,1045.0,NaN,NaN,CA,NaN,NaN,CHEV,PA,BK,1246 S FIGUEROA ST,1L20,1.0,8069AP,NO STOP/STAND PM,93.0,99999.0,99999.0
19,1107780811,2015-12-22T00:00:00,1102.0,NaN,NaN,CA,201606.0,NaN,HOND,PA,BK,PLATA/RAMPART,2A1,1.0,8069B,NO PARKING,73.0,99999.0,99999.0
21,1107973985,2015-12-18T00:00:00,1920.0,NaN,NaN,CA,201509.0,NaN,NISS,PA,BK,VICAR/CASTLE HEIGHTS,8A95,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
22,1107973996,2015-12-18T00:00:00,1930.0,NaN,NaN,CA,201511.0,NaN,HOND,PA,BK,REGENT ST/IVY ST,8A95,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
25,1108311013,2015-12-22T00:00:00,150.0,NaN,NaN,CA,201610.0,NaN,FORD,SU,GY,6936 AGNES AV,01514,1.0,5200A,DSPLYPLATE A,25.0,99999.0,99999.0
29,1108311050,2015-12-22T00:00:00,510.0,NaN,NaN,CA,201601.0,NaN,TESL,PA,GY,11411 DONA PEGITA DR,NaN,1.0,5200A,DSPLYPLATE A,25.0,99999.0,99999.0
30,1108319494,2015-12-22T00:00:00,135.0,NaN,NaN,CA,201601.0,NaN,MBNZ,PA,WH,12355 BURBANK BL,01503,1.0,5200A,DSPLYPLATE A,25.0,99999.0,99999.0
31,1108321701,2015-12-21T00:00:00,926.0,NaN,NaN,CA,201510.0,NaN,ACUR,PA,BK,5741 FLUTCHER AVE,15EL5,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
32,1108321712,2015-12-21T00:00:00,935.0,NaN,NaN,CA,201506.0,NaN,TOYO,PA,SI,5611 FLUTCHER AVE,15EL5,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
35,1108347984,2015-12-09T00:00:00,1250.0,NaN,NaN,CA,201511.0,NaN,SUBA,PA,MA,GRAND AVE/57TH ST,00013,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
37,1109056185,2015-12-28T00:00:00,1938.0,WF55,NaN,CA,201512.0,NaN,ACUR,PA,GY,100 S HARPER AV,00472,54.0,8813B,METER EXPIRED,63.0,99999.0,99999.0
41,1109056222,2015-12-28T00:00:00,1955.0,WF100,NaN,CA,201601.0,NaN,NISS,PA,SI,100 S ORLANDO,00472,54.0,8813B,METER EXPIRED,63.0,99999.0,99999.0
43,1109455266,2015-12-26T00:00:00,1815.0,NaN,NaN,NY,NaN,NaN,TOYO,PA,WH,3200 CANYON DR,NaN,36.0,8603,PK IN PROH AREA,68.0,6467477.1,1868721.0
47,1109484191,2015-12-16T00:00:00,100.0,NaN,NaN,CA,201508.0,NaN,NISS,PA,BK,TOBERMAN N/O 18TH ST,2A45,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
50,1109486545,2015-12-16T00:00:00,1245.0,NaN,NaN,CA,201602.0,NaN,NISS,PA,BL,2504 JAMES M WOOD,00261,1.0,8056E4,RED ZONE,93.0,99999.0,99999.0
52,1109704923,2015-12-28T00:00:00,845.0,NaN,NaN,CA,201606.0,NaN,ACUR,PA,BK,1606 N LAUREL AV,NaN,54.0,8069BS,NO PARK/STREET CLEAN,73.0,99999.0,99999.0
56,1109811360,2015-12-26T00:00:00,2231.0,NaN,NaN,CA,201506.0,NaN,SCIO,SU,BK,1141 EAGLE VISTA DR,NaN,36.0,8603,PK IN PROH AREA,68.0,6504463.3,1874621.5
58,1109818625,2015-12-27T00:00:00,2235.0,NaN,NaN,CA,201601.0,NaN,CADI,PA,BK,2551 MOTOR AVE,NaN,34.0,6344K2,NO PK BET 1-3AM,68.0,6438048.2,1839690.7
59,1109926252,2015-12-18T00:00:00,738.0,NaN,NaN,CA,201508.0,NaN,KIA,PA,WH,CATTARAUGUS AVE/HOLT,8A95,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
64,1110245776,2015-12-16T00:00:00,200.0,NaN,NaN,CA,201504.0,NaN,FREI,TR,RE,IMPERIAL/LA CIENEGA,NaN,1.0,018,22502A,63.0,99999.0,99999.0

In [12]:
print(tic_mod.groupby('Top25')['Top25'].size().sort_values(ascending=False))

KeyError: 'Top25'

In [54]:
print(tickets.groupby('RP State Plate')['RP State Plate'].size().sort_values(ascending=False).head(10))

print(tickets.groupby('Violation Description')['Violation Description'].size().sort_values(ascending=False))

print(tickets.groupby('Make')['Make'].size().sort_values(ascending=False).head(25))

# tickets.groupby(['RP State Plate']) \
#                              .count() \
#                              .reset_index(name='count') \
#                              .sort_values(['count'], ascending=False) \
#                              .head(5)

#df.groupby(["name"]).apply(lambda x: x.sort_values(["count_1"], ascending = False)).reset_index(drop=True)

RP State Plate
CA    8127986
AZ      77649
TX      55337
NV      51944
FL      37924
WA      34585
IL      24995
OR      24291
CO      22167
NY      16261
Name: RP State Plate, dtype: int64
Violation Description
NO PARK/STREET CLEAN              2530294
METER EXP.                        1524589
RED ZONE                           646198
PREFERENTIAL PARKING               599200
DISPLAY OF TABS                    535798
NO PARKING                         390111
DISPLAY OF PLATES                  239502
WHITE ZONE                         194981
NO STOP/STANDING                   157259
PARKED OVER TIME LIMIT             154205
PARKED OVER TIME LIM               136763
STANDNG IN ALLEY                   122059
BLOCKING DRIVEWAY                  108708
STOP/STAND PROHIBIT                 96424
YELLOW ZONE                         92035
NO STOP/STAND                       89075
NO EVIDENCE OF REG                  86887
PARKED ON SIDEWALK                  79419
18 IN. CURB/2 WAY                   76348
EXCEED 72HRS-ST                     74313
FIRE HYDRANT                        68157
DOUBLE PARKING                      57569
OUTSIDE LINES/METER                 53880
NO STOPPING/ANTI-GRIDLOCK ZONE      52885
OFF STR/OVERTIME/MTR                45579
NO STOPPING/ANTI-GRI                40488
EXPIRED TAGS                        26110
COMM VEH OVER TIME LIMIT            20097
PRIVATE PROPERTY                    18416
METER EXPIRED                       17992
                                   ...
4001A                                   1
4001A1                                  1
4008                                    1
4118                                    1
8058                                    1
4119                                    1
4200A1                                  1
8056A                                   1
8060E                                   1
80611                                   1
28869B                                  1
27900                                   1
80661B                                  1
26700A                                  1
80661A                                  1
26706                                   1
806601D                                 1
8064                                    1
80632                                   1
267086                                  1
80622                                   1
8061D                                   1
8061A                                   1
26708AE                                 1
26708B                                  1
26708CA1                                1
80611D                                  1
27465B1                                 1
27500H                                  1
08062                                   1
Name: Violation Description, Length: 795, dtype: int64
Make
TOYT    721411
HOND    491961
FORD    382695
NISS    311324
CHEV    297076
BMW     199221
MERZ    177307
VOLK    149501
HYUN    133864
DODG    127764
LEXS    124508
KIA     101746
JEEP    100909
AUDI     84229
MAZD     79853
OTHR     72411
GMC      62391
CHRY     57317
INFI     56809
ACUR     52703
SUBA     46898
VOLV     42330
TOYO     40064
MITS     37842
CADI     34080
Name: Make, dtype: int64

In [15]:
tickets[tickets['Violation Description'].str.lower().str.contains('tag')==True]

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
68,1110265251,2015-12-16T00:00:00,1340.0,NaN,NaN,CA,NaN,NaN,NaN,TR,WH,ORION AVE/SHERMAN WY,22MP4,1.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
100,1112006442,2015-12-24T00:00:00,1000.0,NaN,NaN,CA,201507.0,NaN,CADI,PA,BK,251 WORLD WAY,1R2,2.0,5204A,EXPIRED TAGS,25.0,6.438218e+06,1.802453e+06
101,1112006453,2015-12-24T00:00:00,NaN,NaN,NaN,CA,201508.0,NaN,HYUN,PA,GY,251 WORLD WAY,1R2,2.0,5204A,EXPIRED TAGS,25.0,6.438218e+06,1.802453e+06
110,1112058802,2015-12-10T00:00:00,1245.0,NaN,NaN,CA,201509.0,NaN,NaN,PA,BL,7610 WOODLEY AVE,1C12,11.0,5204A,EXPIRED TAGS,25.0,6.415432e+06,1.898663e+06
111,1112058813,2015-12-12T00:00:00,1850.0,NaN,NaN,CA,201601.0,NaN,NaN,PA,BL,7610 WOODLEY AVE,2C12,11.0,5204A,EXPIRED TAGS,25.0,6.415432e+06,1.898663e+06
112,1112058824,2015-12-12T00:00:00,1900.0,NaN,NaN,CA,201701.0,NaN,NaN,PA,GY,7610 WOODLEY AVE,2C12,11.0,5204A,EXPIRED TAGS,25.0,6.415432e+06,1.898663e+06
114,1112058846,2015-12-12T00:00:00,1920.0,NaN,NaN,CA,201506.0,NaN,NaN,PA,BR,7610 WOODLEY AVE,2C12,11.0,5204A,EXPIRED TAGS,25.0,6.415432e+06,1.898663e+06
115,1112058850,2015-12-12T00:00:00,1925.0,NaN,NaN,CA,201601.0,NaN,FORD,PA,WH,7610 WOODLEY AVE,2C12,11.0,5204A,EXPIRED TAGS,25.0,6.415432e+06,1.898663e+06
116,1112058872,2015-12-17T00:00:00,1905.0,NaN,NaN,AR,201608.0,NaN,NaN,NaN,BL,7610 WOODLEY AVE,2C12,11.0,5204A,EXPIRED TAGS,25.0,6.415432e+06,1.898663e+06
117,1112058883,2015-12-17T00:00:00,1915.0,NaN,NaN,CA,201509.0,NaN,NISS,PA,WH,7610 WOODLEY AVE,2C12,11.0,5204A,EXPIRED TAGS,25.0,6.415432e+06,1.898663e+06
118,1112058894,2015-12-17T00:00:00,1920.0,NaN,NaN,CA,201509.0,NaN,TOYO,PA,BR,7610 WOODLEY AVE,2C12,11.0,5204A,EXPIRED TAGS,25.0,6.415432e+06,1.898663e+06
127,1112069976,2015-12-23T00:00:00,439.0,NaN,NaN,CA,201506.0,NaN,NaN,PA,BK,101 WORLD WAY,3A206,2.0,5204A,EXPIRED TAGS,25.0,6.439738e+06,1.802687e+06
128,1112070411,2015-12-23T00:00:00,1720.0,NaN,NaN,CA,201508.0,NaN,BMW,PA,GY,299 WORLD WY,2B1,2.0,5204A,EXPIRED TAGS,25.0,6.437974e+06,1.802395e+06
129,1112070422,2015-12-23T00:00:00,1745.0,NaN,NaN,CA,201504.0,NaN,MBNZ,PA,BK,251 WORLD WY,2B1,2.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
146,1112078214,2015-12-08T00:00:00,1700.0,NaN,NaN,CA,201509.0,NaN,NaN,TR,BK,401 W/W 4D,00024,2.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
150,1112078660,2015-12-14T00:00:00,815.0,NaN,NaN,CA,201508.0,NaN,TOYO,PA,SI,7610 WOODLEY AVE,1L5,11.0,5204A,EXPIRED TAGS,25.0,6.415432e+06,1.898663e+06
153,1112078693,2015-12-14T00:00:00,850.0,NaN,NaN,CA,201506.0,NaN,NaN,PA,GY,7610 WOODLEY AVE,1L5,11.0,5204A,EXPIRED TAGS,25.0,6.415432e+06,1.898663e+06
159,1112079172,2015-12-24T00:00:00,1020.0,NaN,NaN,CA,201510.0,NaN,NaN,PA,WH,251 WORLD WAY,1F21,2.0,5204A,EXPIRED TAGS,25.0,6.438218e+06,1.802453e+06
160,1112079183,2015-12-24T00:00:00,1005.0,NaN,NaN,CA,201506.0,NaN,NaN,PA,BK,251 WORLD WAY,1F21,2.0,5204A,EXPIRED TAGS,25.0,6.438218e+06,1.802453e+06
222,1112099004,2015-12-15T00:00:00,1525.0,NaN,NaN,CA,201508.0,NaN,AUDI,PA,GY,301 W/W 1D,00024,2.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
223,1112099015,2015-12-15T00:00:00,1540.0,NaN,NaN,CA,201507.0,NaN,NaN,PA,GY,301 W/W 2D,00024,2.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
269,1112718025,2015-12-28T00:00:00,1222.0,NaN,NaN,CA,201510.0,NaN,NaN,PA,GR,1843 N RODNEY DR,00461,54.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
272,1112718051,2015-12-28T00:00:00,1240.0,NaN,NaN,CA,201509.0,NaN,NaN,PA,WH,5041 W FRANKLIN AV,00461,54.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
277,1112741825,2015-12-18T00:00:00,1020.0,NaN,NaN,CA,201511.0,NaN,INFI,PA,SI,21900 SCHOENBORN ST,35MQ2,1.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
8030,1109579590,2015-12-28T00:00:00,832.0,NaN,NaN,CA,201509.0,NaN,CHEV,PA,WH,1559 W 71ST ST,00545,55.0,5204A,EXPIRED TAGS,25.0,6.469580e+06,1.813562e+06
8036,1109579656,2015-12-28T00:00:00,845.0,NaN,NaN,CA,201408.0,NaN,NaN,PA,GR,7100 S HALLDALE AVE,00545,55.0,5204A,EXPIRED TAGS,25.0,6.469973e+06,1.813561e+06
8045,1109579741,2015-12-28T00:00:00,927.0,NaN,NaN,CA,201504.0,NaN,NaN,PA,BR,1029 W 66TH ST,00545,55.0,5204A,EXPIRED TAGS,25.0,6.473100e+06,1.814926e+06
8054,1109580581,2015-12-27T00:00:00,1029.0,NaN,NaN,CA,201410.0,NaN,TOYO,PA,TA,5902 S BUCKER AVE,00500,55.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
8056,1109580603,2015-12-27T00:00:00,1304.0,NaN,NaN,CA,200710.0,NaN,NaN,TR,GR,1100 W 65TH ST,00500,55.0,5204A,EXPIRED TAGS,25.0,6.472632e+06,1.815422e+06
8076,1109580802,2015-12-28T00:00:00,1006.0,NaN,NaN,CA,201503.0,NaN,CADI,PA,WH,1513 W 67TH ST,00545,55.0,5204A,EXPIRED TAGS,25.0,6.469899e+06,1.814696e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8710762,1127209230,2018-12-27T00:00:00,913.0,NaN,NaN,CA,201709.0,NaN,NaN,PA,RE,7610 WOODLEY,1L5,11.0,5204A,EXPIRED TAGS,25.0,6.415432e+06,1.898663e+06
8710766,1127211341,2018-12-27T00:00:00,930.0,NaN,NaN,CA,201804.0,NaN,NaN,PA,BE,7610 WOODLEY,1L5,11.0,5204A,EXPIRED TAGS,25.0,6.415432e+06,1.898663e+06
8710767,1127211352,2018-12-27T00:00:00,940.0,NaN,NaN,CA,201805.0,NaN,NaN,PA,GY,7610 WOODLEY,1L5,11.0,5204A,EXPIRED TAGS,25.0,6.415432e+06,1.898663e+06
8710769,1127211374,2018-12-28T00:00:00,1005.0,NaN,NaN,CA,201809.0,NaN,TOYO,PA,WH,7610 WOODLEY,1A4,11.0,5204A,EXPIRED TAGS,25.0,6.415432e+06,1.898663e+06
8710773,1127211411,2018-12-28T00:00:00,1030.0,NaN,NaN,CA,201811.0,NaN,NaN,PA,WH,7610 WOODLEY,1A4,11.0,5204A,EXPIRED TAGS,25.0,6.415432e+06,1.898663e+06
8710796,1127260746,2019-01-06T00:00:00,1340.0,NaN,NaN,CA,201805.0,NaN,GENE,PA,WH,401 WORLD WAY (4F),1F92,2.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
8710805,1127273206,2018-12-31T00:00:00,835.0,NaN,NaN,CA,201906.0,NaN,NaN,NaN,BK,701 WORLD WAY,5M45,2.0,5204A,EXPIRED TAGS,25.0,6.439825e+06,1.801814e+06
8710806,1127273210,2018-12-31T00:00:00,845.0,NaN,NaN,CA,201906.0,NaN,MAZD,PA,WH,701 WORLD WAY,5M45,2.0,5204A,EXPIRED TAGS,25.0,6.439825e+06,1.801814e+06
8710808,1127273232,2018-12-31T00:00:00,1035.0,NaN,NaN,CA,201907.0,NaN,NaN,PA,GY,401 WORLD WAY,5M45,2.0,5204A,EXPIRED TAGS,25.0,6.437904e+06,1.801968e+06
8710809,1127273243,2018-12-31T00:00:00,1230.0,NaN,NaN,CA,201907.0,NaN,NaN,TR,GY,5625 IMPERIAL,5M45,2.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
8710816,1127275505,2019-01-01T00:00:00,1210.0,NaN,NaN,CA,201906.0,NaN,NaN,PA,WH,301 WORLD WAY,5M45,2.0,5204A,EXPIRED TAGS,25.0,6.437964e+06,1.802393e+06
8710818,1127275520,2019-01-02T00:00:00,1725.0,NaN,NaN,CA,201904.0,NaN,NaN,PA,BL,301 WORLD WAY,5M45,2.0,5204A,EXPIRED TAGS,25.0,6.437964e+06,1.802393e+06
8710820,1127275542,2019-01-02T00:00:00,1755.0,NaN,NaN,CA,201907.0,NaN,MERC,PA,WH,301 WORLD WAY,5M45,2.0,5204A,EXPIRED TAGS,25.0,6.437964e+06,1.802393e+06
8710822,1127275564,2019-01-03T00:00:00,1055.0,NaN,NaN,CA,201901.0,NaN,NaN,PA,BK,301 WORLD WAY,5M45,2.0,5204A,EXPIRED TAGS,25.0,6.437964e+06,1.802393e+06
8710831,1127287162,2019-01-01T00:00:00,1210.0,NaN,NaN,CA,201906.0,NaN,TOYO,PA,BK,401 WORLD WAY,5M31,2.0,5204A,EXPIRED TAGS,25.0,6.437904e+06,1.801968e+06
8710837,1127287755,2018-12-31T00:00:00,1230.0,NaN,NaN,CA,201910.0,NaN,CADI,PA,BK,401 WORLD WAY 3B,5M42,2.0,5204A,EXPIRED TAGS,25.0,6.437904e+06,1.801968e+06
8710839,1127287770,2018-12-31T00:00:00,1245.0,NaN,NaN,CA,201908.0,NaN,HOND,PA,GY,401 WORLD WAY 3D,5M42,2.0,5204A,EXPIRED TAGS,25.0,6.437904e+06,1.801968e+06
8710850,1127293370,2018-12-31T00:00:00,1050.0,NaN,NaN,CA,201802.0,NaN,TOYO,PA,BL,9019 S AIRPORT BLVD,5M28,2.0,5204A,EXPIRED TAGS,25.0,6.444687e+06,1.806252e+06
8710851,1127293381,2018-12-31T00:00:00,1058.0,NaN,NaN,CA,201803.0,NaN,CHEV,PA,GR,9019 S AIRPORT BLVD,5M28,2.0,5204A,EXPIRED TAGS,25.0,6.444687e+06,1.806252e+06
8710852,1127293392,2018-12-31T00:00:00,1103.0,NaN,NaN,CA,201803.0,NaN,DODG,PA,GY,9019 S AIRPORT BLVD,5M28,2.0,5204A,EXPIRED TAGS,25.0,6.444687e+06,1.806252e+06
8710853,1127293403,2018-12-31T00:00:00,1106.0,NaN,NaN,CA,201801.0,NaN,NaN,PA,RE,9019 S AIRPORT BLVD,5M28,2.0,5204A,EXPIRED TAGS,25.0,6.444687e+06,1.806252e+06
8710856,1127293436,2019-01-02T00:00:00,1924.0,NaN,NaN,CA,201807.0,NaN,NaN,PA,WH,100 WORLD WAY,5M25,2.0,5204A,EXPIRED TAGS,25.0,6.440041e+06,1.802686e+06
8717898,1088419323,2018-12-31T00:00:00,1125.0,NaN,NaN,CA,201909.0,NaN,CHEV,PA,SI,SUNSET/BELLEVUE,2A39,1.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
8717927,1113254376,2019-01-01T00:00:00,1740.0,NaN,NaN,CA,201808.0,NaN,NaN,VN,WH,SAN FERNANDO/HALLETT,24MX2,1.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
8717930,1113254402,2019-01-01T00:00:00,1910.0,NaN,NaN,CA,201711.0,NaN,NaN,PA,BL,SAN FERNANDO/EDWARD,24MX2,1.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
8718137,1120620502,2019-01-05T00:00:00,230.0,NaN,NaN,CA,201906.0,NaN,NaN,PA,WH,ELMYRA E/O N MAIN,1Z45,1.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
8718138,1120620513,2019-01-05T00:00:00,235.0,NaN,NaN,CA,201905.0,NaN,NaN,PA,BK,ELMYRA/MAGDALENA,1Z45,1.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
8718160,1120627955,2019-01-03T00:00:00,1425.0,NaN,NaN,CA,201811.0,NaN,NaN,TR,WH,5TH W/O GLADYS AVE,1FB4,1.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
8718359,1125895540,2019-01-03T00:00:00,1606.0,NaN,NaN,CA,201811.0,NaN,NaN,PA,WH,2200 W OLYMPIC BLVD,00041,56.0,5204A,EXPIRED TAGS,25.0,9.999900e+04,9.999900e+04
8718408,1126637536,2019-01-08T00:00:00,1325.0,NaN,NaN,CA,201808.0,NaN,NaN,VN,WH,3317 N JEFFRIES AV,645B,56.0,5204A,EXPIRED TAGS,25.0,6.494859e+06,1.854421e+06

In [116]:
tic_mod['Residency'] = tic_mod['RP State Plate'].apply(lambda x: 'In State' if  x == 'CA' else 'Out of State')
tic_mod['Expired Plates'] = tic_mod[]

In [ ]:
tic_mod['']

In [117]:
tic_mod.head()

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,...,Violation code,Violation Description,Fine amount,Latitude,Longitude,Issue Date Fixed,Plate Expiry Date Num,Plate String,Plate Expiry Date Fixed,Residency
1,1106500452,2015-12-17T00:00:00,1710.0,NaN,NaN,CA,201605.0,NaN,MAZD,PA,...,8070,PARK IN GRID LOCK ZN,163.0,99999.0,99999.0,2015-12-17,201605,201605,2016-05-01,In State
2,1106506424,2015-12-22T00:00:00,1100.0,NaN,NaN,CA,201511.0,NaN,FORD,TR,...,8069AA,NO STOP/STAND AM,93.0,99999.0,99999.0,2015-12-22,201511,201511,2015-11-01,In State
3,1106506435,2015-12-22T00:00:00,1105.0,NaN,NaN,CA,201701.0,NaN,CHRY,PA,...,8069AA,NO STOP/STAND AM,93.0,99999.0,99999.0,2015-12-22,201701,201701,2017-01-01,In State
4,1107179581,2015-12-27T00:00:00,1055.0,NaN,NaN,CA,201605.0,NaN,TOYO,PA,...,8058L,PREF PARKING,68.0,99999.0,99999.0,2015-12-27,201605,201605,2016-05-01,In State
6,1107780811,2015-12-22T00:00:00,1102.0,NaN,NaN,CA,201606.0,NaN,HOND,PA,...,8069B,NO PARKING,73.0,99999.0,99999.0,2015-12-22,201606,201606,2016-06-01,In State

In [49]:
tickets[['Residency']][tickets['Violation Description']=='EXPIRED TAGS'].groupby('Residency').size()

Residency
In State        25642
Out of State      468
dtype: int64

In [51]:
tickets[['Residency']].groupby('Residency').size()

Residency
In State        8127986
Out of State     598028
dtype: int64